-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."users"
(
    id  SERIAL  NOT NULL,
    email varchar(50) NOT NULL,
    password varchar(20) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."workers"
(
    "employee_id" integer NOT NULL,
    "first_name" varchar(20) NOT NULL,
    "last_name" varchar(20) NOT NULL,
    "identification_number" varchar(11) NOT NULL,
    "birth_year" integer NOT NULL,
    "email_verify" boolean,
    PRIMARY KEY ("employee_id")
);

CREATE TABLE public."employers"
(
    "employer_id" integer NOT NULL,
    "company_name" varchar(30) NOT NULL,
    "web_site" varchar(40) NOT NULL,
	"phone_number" varchar(15) NOT NULL,
    "email_verify" boolean,
    "admin_verify" boolean,
    PRIMARY KEY ("employer_id")
);

CREATE TABLE public."jobs"
(
    id SERIAL NOT NULL,
    "job_name" varchar(20) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."systemPersonels"
(
    "personel_id" integer NOT NULL,
    "role_id" integer NOT NULL,
    "firs_name" varchar(20) NOT NULL,
    "last_name" varchar(20) NOT NULL,
    PRIMARY KEY ("personel_id")
);

CREATE TABLE public."roles"
(
    id SERIAL NOT NULL,
    "role_name" varchar(20) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public."users"
    ADD FOREIGN KEY (id)
    REFERENCES public."workers" ("employee_id")
    NOT VALID;


ALTER TABLE public."users"
    ADD FOREIGN KEY (id)
    REFERENCES public."employers" ("employer_id")
    NOT VALID;


ALTER TABLE public."users"
    ADD FOREIGN KEY (id)
    REFERENCES public."systemPersonels" ("personel_id")
    NOT VALID;


ALTER TABLE public."systemPersonels"
    ADD FOREIGN KEY ("role_id")
    REFERENCES public."roles" (id)
    NOT VALID;

END;
